In [1]:
#Numpy Lab Anudip


import numpy as np

In [3]:
#create array elements between 25 to 45(20 elements).Arrange them in equal size array

arr1 = np.arange(25,45).reshape((2,10))
print(arr1)

[[25 26 27 28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41 42 43 44]]


In [4]:
#find array element greater than 10

array = np.array([15,13,4,5,7,80,65,10,2])
extract_ele = np.extract(array > 10, array)
print(extract_ele)

[15 13 80 65]


In [7]:
#concatenate two array apply all mathematical operator on the same

array1 = np.array([1,3,5,7,9])
array2 = np.array([2,4,6,8,10])
concatenate_arr = np.concatenate((array1,array2))
print("Concatenated array:", concatenate_arr)

Concatenated array: [ 1  3  5  7  9  2  4  6  8 10]


In [9]:
# Extract all odd numbers from array

arr = np.array([1,2,3,4,5,6,7,8,9,10])

extract_odd = arr[arr % 2 != 0]
print("Odd numbers from arr1:",extract_odd)

Odd numbers from arr1: [1 3 5 7 9]
